baseURL = 'https://taniwritescode.dev'
languageCode = 'en-us'

title = 'Tani Nevins-Klein'
theme = 'stanza'
sectionPagesMenu = 'main'

paginate = 10

[params]
description = 'Rúcǐ zhēnshí de hǎo péngyǒu!'

githubUsername = "tnevins-klein"
discordUsername = "epsilondeltafan"
instagramUsername = "unclearlines"

frontPageImage = "/img/bg_alt.png"
utterancesRepo = "tnevins-klein/blog"